version: '3.1'

services:

  mongodb:
     image: mongo:4.2.1-bionic
     expose:
        - 27017
     volumes:
       - mongodb-data:/data/db
     restart: always
     environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSSWD}


  nodejs:
     image: tempmail 
     depends_on: 
      - mongodb
     ports:
      - "80:3000"
      - "25:25"
     restart: always
     env_file: ".env"
     links:
      - mongodb

volumes:
  mongodb-data:
